name = "Dataverse"
uuid = "9c0b9be8-e31e-490f-90fe-77697562404d"
authors = ["gaelforget <gforget@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
